### ISSUE TITLE
Error transforming multiple patterns

### ISSUE THREAD

**Issue by shenlong** [outaTiME/gulp-replace-task#5]
I am using the following pattern to modify the php file:

``` javascript
    patterns: [
        {
            match: /\$domain\s*=\s*["'](.*?)["'];(?!(?:(?!\/\*)[\S\s])*\*\/)/g,
            replacement: [Function]
        },
        {
            match: /\$clientId\s*=\s*["'](.*?)["'];(?!(?:(?!\/\*)[\S\s])*\*\/)/g,
            replacement: [Function]
        },
        {
            match: /\$clientName\s*=\s*["'](.*?)["'];(?!(?:(?!\/\*)[\S\s])*\*\/)/g,
            replacement: [Function]
        },
        {
            match: /\$accountId\s*=\s*["'](.*?)["'];(?!(?:(?!\/\*)[\S\s])*\*\/)/g,
            replacement: [Function]
        }]
```

to match my php file:

``` php
// php file.
$domain = "https://api.myhost.local";
$clientId = 'cilentId01';
$clientName= 'Client 01';
$accountId = 'new-2a123121ce-412312-4841-bdd7-7e12316sa0';
/* Do not modify comment:
$accountId = 'comment-2a123121ce-412312-4841-bdd7-7e12316sa0';
*/
```

I got this error:

```
buffer.js:249
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: must start with number, buffer, array or string
  at fromObject (buffer.js:249:9)
  at Function.Buffer.from (buffer.js:115:10)
  at new Buffer (buffer.js:94:17)
  at DestroyableTransform._transform (c:\Projects\node_modules\gulp-replace-task\index.js:44:23)
```

This is the offending code:

```
// gulp-replace-task/index.js file at line 43:
    if (result !== false) {
      file.contents = new Buffer(result);
    } else {
      // preserve original file
    }
```

Changing the code to result.content seems to fix the issue.

```
  if (result !== false) {
      file.contents = new Buffer(result.content);
    } else {
      // preserve original file
    }
```

I am on version 2015-09-09 v0.11.0

Is there implications? Or can it be official fix?

**Comment by shenlong** [comment]
I have changed the code to:

```
    if (result !== false) {
      if (result.count > 1){
        file.contents = new Buffer(result.content);
      }
      else {
        file.contents = new Buffer(result);
      }
    } else {
      // preserve original file
    }
```

As there TypeError for simple replace. Not sure the implications. to use result.count.

**Comment by outaTiME** [comment]
Hi @shenlong, 
sorry im away from code for a few months ... i will check your solution, soon im releasing a new version with few enhancements.

Thanks !!!

**Comment by outaTiME** [comment]
Sorry, finally after so much time I updated the dependencies in the new version of this plugin to fix the incompatibility and vulnerabilities problems.
